In [1]:
import numpy as np
import cv2

In [2]:
image=cv2.imread(r"C:\Users\DELL\Downloads\cat-dog-elephant\elephant\elephantelephant887.jpg")

In [4]:
image.shape

(432, 768, 3)

## translation ##

In [4]:
tx=-50 # here we give tx value is positive it moves towards right side,negative left side
ty=10 # here we give ty value is positive it slidly moves down,negative up
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)# here we are translating the image
t_img=cv2.warpAffine(image,t_m,(768,432))

In [5]:
t_m

array([[  1.,   0., -50.],
       [  0.,   1.,  10.]], dtype=float32)

In [13]:
cv2.imshow("orginal_image",image)
cv2.imshow("translation_image",t_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
tx=50
ty=0
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)
t_img=cv2.warpAffine(image,t_m,(768,432),borderMode=cv2.BORDER_CONSTANT,borderValue=(0,0,255))

In [ ]:
cv2.imshow("orginal_image",image)
cv2.imshow("translation_image",t_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
tx=50
ty=0
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)
t_img=cv2.warpAffine(image,t_m,(768,432),borderMode=cv2.BORDER_REFLECT)


In [ ]:
cv2.imshow("orginal_image",image)
cv2.imshow("translation_image",t_img)
cv2.waitKey()
cv2.destroyAllWindows()

## rotation

In [3]:
image1=cv2.imread(r"C:\Users\DELL\Downloads\pikachu.jpg")

In [4]:
image1.shape

(225, 225, 3)

In [5]:
225//2

112

In [6]:
r_m=cv2.getRotationMatrix2D((112,112),90,1)


In [7]:
r_m

array([[ 6.12323400e-17,  1.00000000e+00, -1.42108547e-14],
       [-1.00000000e+00,  6.12323400e-17,  2.24000000e+02]])

In [16]:
r_image1=cv2.warpAffine(image1,r_m,(225,225))


In [17]:
cv2.imshow("orginal_image",image1)
cv2.imshow("rotational_image",r_image1)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
r_image1=cv2.warpAffine(image1,r_m,(225,225))
r_image2=cv2.warpAffine(image1,r_m,(225,225))
r_image3=cv2.warpAffine(image1,r_m,(225,225))

In [9]:
image1=cv2.rotate(image1,cv2.ROTATE_180)
image2=cv2.rotate(image1,cv2.ROTATE_90_CLOCKWISE)
image3=cv2.rotate(image1,cv2.ROTATE_90_COUNTERCLOCKWISE)


In [10]:
cv2.imshow("orginal_image",image1)
cv2.imshow("rotational_image1",r_image1)
cv2.imshow("rotational_image2",r_image2)
cv2.imshow("rotational_image2",r_image3)
cv2.waitKey()
cv2.destroyAllWindows()

## scaling

In [13]:
image=cv2.imread(r"C:\Users\DELL\Downloads\pikachu.jpg")

In [14]:
image.shape

(225, 225, 3)

In [19]:
sx=3
sy=1
tx=0
ty=0
sc_m=np.array([[sx,0,tx],[0,sy,ty]],dtype=np.float32)

In [16]:
sc_m

array([[3., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [20]:
scl_img=cv2.warpAffine(image,sc_m,(225,225))
cv2.imshow("orginal_image",image)
cv2.imshow("scaling_image",scl_img)
cv2.waitKey()
cv2.destroyAllWindows()


## defailt parameters

In [23]:
zoom_in=cv2.pyrDown(image)
zoom_out=cv2.pyrUp(image)

In [24]:
cv2.imshow("orginal_image",zoom_in)
cv2.imshow("scaling_image",zoom_out)
cv2.waitKey()
cv2.destroyAllWindows()

## sheering

In [25]:
shx=1
shy=0
tx=0
ty=0
sh_m=np.array([[1,shx,tx],[shy,1,ty]],dtype=np.float32)

In [26]:
shm_img=cv2.warpAffine(image,sh_m,(225,225))
cv2.imshow("orginal_image",image)
cv2.imshow("scaling_image",shm_img)
cv2.waitKey()
cv2.destroyAllWindows()


## cropping

In [2]:
image=cv2.imread(r"C:\Users\DELL\Downloads\pikachu.jpg")

In [3]:
cr_img=image[10:90,15:100]

In [4]:
cv2.imshow("orginal_image",image)
cv2.imshow("cropping_img",cr_img)
cv2.waitKey()
cv2.destroyAllWindows()